<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KhadyobiranSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // ── Categories ──
        $categories = [
            ['name' => 'Organic Salts',        'slug' => 'organic-salts',       'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Superseeds & Grains',  'slug' => 'superseeds-grains',   'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Natural Sweeteners',   'slug' => 'natural-sweeteners',  'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Premium Dates',        'slug' => 'premium-dates',       'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Organic Oils',         'slug' => 'organic-oils',        'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nuts & Dry Fruits',    'slug' => 'nuts-dry-fruits',     'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Organic Spices',       'slug' => 'organic-spices',      'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Herbal Teas',          'slug' => 'herbal-teas',         'status' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Health Foods',         'slug' => 'health-foods',        'status' => 1, 'created_at' => $now, 'updated_at' => $now],
        ];

        DB::table('categories')->insert($categories);

        // Get inserted category IDs by slug
        $catIds = DB::table('categories')->pluck('id', 'slug');

        // ── Products ──
        $products = [
            // Organic Salts
            [
                'name'        => 'Himalayan Pink Salt',
                'slug'        => 'himalayan-pink-salt',
                'category_id' => $catIds['organic-salts'],
                'old_price'   => 450,
                'new_price'   => 350,
                'purchase_price' => 200,
                'stock'       => 150,
                'description' => 'Pure, unrefined Himalayan Pink Salt sourced directly from the ancient salt mines of the Himalayan Mountains. Rich in 84 trace minerals including calcium, magnesium, potassium, and iron.',
                'meta_title'  => 'Himalayan Pink Salt – 84 Trace Minerals | Khadyobitan',
                'meta_description' => 'Buy pure Himalayan Pink Salt rich in 84 trace minerals. No preservatives, organic certified.',
                'meta_keyword' => 'himalayan salt, pink salt, organic salt',
                'topsale'     => 1,
                'new_arrival' => 1,
                'top_rated'   => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Sea Salt Flakes',
                'slug'        => 'sea-salt-flakes',
                'category_id' => $catIds['organic-salts'],
                'old_price'   => 350,
                'new_price'   => 290,
                'purchase_price' => 160,
                'stock'       => 80,
                'description' => 'Hand-harvested sea salt flakes with a delicate, crunchy texture. Perfect as a finishing salt for gourmet dishes.',
                'meta_title'  => 'Sea Salt Flakes – Hand-Harvested | Khadyobitan',
                'meta_description' => 'Premium hand-harvested sea salt flakes. No additives, natural minerals.',
                'meta_keyword' => 'sea salt, salt flakes, gourmet salt',
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Black Salt (Kala Namak)',
                'slug'        => 'black-salt-kala-namak',
                'category_id' => $catIds['organic-salts'],
                'old_price'   => 220,
                'new_price'   => 180,
                'purchase_price' => 100,
                'stock'       => 120,
                'description' => 'Traditional Himalayan Black Salt known for its distinct sulphurous aroma. A staple in South Asian cuisine, especially chaat masala and fruit salads.',
                'meta_title'  => 'Black Salt Kala Namak – Digestive Aid | Khadyobitan',
                'meta_description' => 'Organic Kala Namak black salt. Aids digestion, low sodium alternative.',
                'meta_keyword' => 'black salt, kala namak, himalayan black salt',
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Superseeds & Grains
            [
                'name'        => 'Black Chia Seeds',
                'slug'        => 'black-chia-seeds',
                'category_id' => $catIds['superseeds-grains'],
                'old_price'   => 550,
                'new_price'   => 480,
                'purchase_price' => 300,
                'stock'       => 89,
                'description' => 'Premium quality organic Black Chia Seeds packed with omega-3 fatty acids, fiber, and protein. Perfect for smoothies, puddings, and baking.',
                'meta_title'  => 'Organic Black Chia Seeds – Omega-3 Rich | Khadyobitan',
                'meta_description' => 'USDA Organic chia seeds, non-GMO, gluten-free. High in fiber and complete protein.',
                'meta_keyword' => 'chia seeds, black chia, omega-3, superfood',
                'topsale'     => 1,
                'new_arrival' => 1,
                'top_rated'   => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Organic Black Rice',
                'slug'        => 'organic-black-rice',
                'category_id' => $catIds['superseeds-grains'],
                'old_price'   => 400,
                'new_price'   => 320,
                'purchase_price' => 200,
                'stock'       => 45,
                'description' => 'Nutrient-rich Organic Black Rice, also known as "Forbidden Rice," packed with anthocyanins and antioxidants. Nutty flavor and striking color.',
                'meta_title'  => 'Organic Black Rice – Forbidden Rice | Khadyobitan',
                'meta_description' => 'Organic forbidden rice high in antioxidants. Non-GMO, rich in iron and fiber.',
                'meta_keyword' => 'black rice, forbidden rice, organic rice, anthocyanins',
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Organic Quinoa',
                'slug'        => 'organic-quinoa',
                'category_id' => $catIds['superseeds-grains'],
                'old_price'   => 680,
                'new_price'   => 560,
                'purchase_price' => 350,
                'stock'       => 67,
                'description' => 'Premium Organic White Quinoa — a complete protein grain with all nine essential amino acids. Naturally gluten-free.',
                'meta_title'  => 'Organic Quinoa – Complete Protein Grain | Khadyobitan',
                'meta_description' => 'USDA organic quinoa, gluten-free, all essential amino acids. High fiber and mineral rich.',
                'meta_keyword' => 'quinoa, organic quinoa, gluten-free grain, complete protein',
                'topsale'     => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Flax Seeds (Golden)',
                'slug'        => 'golden-flax-seeds',
                'category_id' => $catIds['superseeds-grains'],
                'old_price'   => 380,
                'new_price'   => 320,
                'purchase_price' => 190,
                'stock'       => 95,
                'description' => 'Premium golden flax seeds rich in omega-3 fatty acids, lignans, and dietary fiber. A superfood for heart and digestive health.',
                'meta_title'  => 'Golden Flax Seeds – Omega-3 & Fiber | Khadyobitan',
                'meta_description' => 'Organic golden flax seeds. Rich in omega-3, lignans, and dietary fiber for heart health.',
                'meta_keyword' => 'flax seeds, golden flax, omega-3, fiber, superfood',
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Natural Sweeteners
            [
                'name'        => 'Raw Organic Honey',
                'slug'        => 'raw-organic-honey',
                'category_id' => $catIds['natural-sweeteners'],
                'old_price'   => 780,
                'new_price'   => 650,
                'purchase_price' => 400,
                'stock'       => 78,
                'description' => 'Pure, unprocessed Raw Organic Honey harvested from local beekeepers. Retains all natural enzymes, pollen, and beneficial compounds.',
                'meta_title'  => 'Raw Organic Honey – Unfiltered & Pure | Khadyobitan',
                'meta_description' => 'Natural raw organic honey, unfiltered, antibacterial. Immunity and antioxidant rich.',
                'meta_keyword' => 'raw honey, organic honey, natural honey, unfiltered honey',
                'topsale'     => 1,
                'new_arrival' => 1,
                'top_rated'   => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Khejur Jaggery',
                'slug'        => 'khejur-jaggery',
                'category_id' => $catIds['natural-sweeteners'],
                'old_price'   => 350,
                'new_price'   => 280,
                'purchase_price' => 160,
                'stock'       => 110,
                'description' => 'Traditional Date Palm Jaggery (Khejur Gur) made from the sap of date palm trees. Rich, caramel-flavored natural sweetener packed with iron.',
                'meta_title'  => 'Khejur Jaggery – Date Palm Gur | Khadyobitan',
                'meta_description' => 'Traditional khejur gur (date palm jaggery). Iron-rich, natural sweetener, low glycemic.',
                'meta_keyword' => 'khejur gur, date palm jaggery, natural sweetener, iron',
                'top_selling' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Organic Coconut Sugar',
                'slug'        => 'organic-coconut-sugar',
                'category_id' => $catIds['natural-sweeteners'],
                'old_price'   => 490,
                'new_price'   => 420,
                'purchase_price' => 260,
                'stock'       => 55,
                'description' => 'Unrefined coconut sugar made from the sap of coconut palm blossoms. A lower glycemic alternative to regular sugar with a rich caramel flavor.',
                'meta_title'  => 'Organic Coconut Sugar – Low GI Sweetener | Khadyobitan',
                'meta_description' => 'Unrefined organic coconut sugar. Low glycemic index, mineral rich, 1:1 sugar substitute.',
                'meta_keyword' => 'coconut sugar, low GI sugar, organic sweetener',
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Premium Dates
            [
                'name'        => 'Premium Medjool Dates',
                'slug'        => 'premium-medjool-dates',
                'category_id' => $catIds['premium-dates'],
                'old_price'   => 1050,
                'new_price'   => 890,
                'purchase_price' => 550,
                'stock'       => 62,
                'description' => 'The king of dates — large, soft, and incredibly sweet Premium Medjool Dates sourced from the finest date farms.',
                'meta_title'  => 'Premium Medjool Dates – King of Dates | Khadyobitan',
                'meta_description' => 'Organic premium Medjool dates. Natural energy, high fiber, rich in potassium.',
                'meta_keyword' => 'medjool dates, premium dates, organic dates',
                'topsale'     => 1,
                'top_rated'   => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Ajwa Dates',
                'slug'        => 'ajwa-dates',
                'category_id' => $catIds['premium-dates'],
                'old_price'   => 1700,
                'new_price'   => 1450,
                'purchase_price' => 900,
                'stock'       => 35,
                'description' => 'Premium Ajwa Dates from Madinah — known for their distinctive dark color, soft texture, and rich, caramel-like flavor with spiritual significance.',
                'meta_title'  => 'Ajwa Dates from Madinah – Premium Authentic | Khadyobitan',
                'meta_description' => 'Authentic Ajwa dates from Madinah, Saudi Arabia. Heart protection, rich in antioxidants.',
                'meta_keyword' => 'ajwa dates, madinah dates, saudi dates, authentic ajwa',
                'topsale'     => 1,
                'top_selling' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Stuffed Dates Assortment',
                'slug'        => 'stuffed-dates-assortment',
                'category_id' => $catIds['premium-dates'],
                'new_price'   => 980,
                'purchase_price' => 600,
                'stock'       => 40,
                'description' => 'A gourmet assortment of premium dates stuffed with almonds, walnuts, and pistachios. Coated in dark chocolate and coconut.',
                'meta_title'  => 'Stuffed Dates Assortment – Premium Gift Box | Khadyobitan',
                'meta_description' => 'Gourmet dates stuffed with almonds, walnuts, pistachios. Perfect gift. No added sugar.',
                'meta_keyword' => 'stuffed dates, dates gift box, gourmet dates',
                'new_arrival' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Organic Oils
            [
                'name'        => 'Cold-Pressed Coconut Oil',
                'slug'        => 'cold-pressed-coconut-oil',
                'category_id' => $catIds['organic-oils'],
                'old_price'   => 620,
                'new_price'   => 520,
                'purchase_price' => 320,
                'stock'       => 95,
                'description' => 'Virgin Cold-Pressed Coconut Oil extracted without heat to preserve all natural nutrients. Rich in MCTs and lauric acid.',
                'meta_title'  => 'Cold-Pressed Virgin Coconut Oil – MCT Rich | Khadyobitan',
                'meta_description' => 'Organic cold-pressed coconut oil. Rich in MCTs, lauric acid. For cooking, skin and hair.',
                'meta_keyword' => 'coconut oil, cold pressed coconut oil, virgin coconut oil, MCT',
                'topsale'     => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Extra Virgin Olive Oil',
                'slug'        => 'extra-virgin-olive-oil',
                'category_id' => $catIds['organic-oils'],
                'old_price'   => 980,
                'new_price'   => 850,
                'purchase_price' => 530,
                'stock'       => 55,
                'description' => 'Premium Extra Virgin Olive Oil with a fruity, peppery flavor. Cold-pressed from hand-picked olives for maximum polyphenol content.',
                'meta_title'  => 'Extra Virgin Olive Oil – Cold-Pressed | Khadyobitan',
                'meta_description' => 'Premium Mediterranean extra virgin olive oil. Rich in polyphenols, anti-inflammatory.',
                'meta_keyword' => 'olive oil, extra virgin olive oil, EVOO, cold pressed',
                'top_rated'   => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Cold-Pressed Mustard Oil',
                'slug'        => 'cold-pressed-mustard-oil',
                'category_id' => $catIds['organic-oils'],
                'old_price'   => 450,
                'new_price'   => 380,
                'purchase_price' => 220,
                'stock'       => 130,
                'description' => 'Traditional cold-pressed mustard oil with a pungent, sharp flavor. A staple in South Asian cooking with natural antibacterial properties.',
                'meta_title'  => 'Cold-Pressed Mustard Oil – Traditional | Khadyobitan',
                'meta_description' => 'Organic cold-pressed mustard oil. Antibacterial, omega-3 rich, traditional South Asian cooking oil.',
                'meta_keyword' => 'mustard oil, cold pressed mustard oil, organic mustard oil',
                'top_selling' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Nuts & Dry Fruits
            [
                'name'        => 'California Almonds',
                'slug'        => 'california-almonds',
                'category_id' => $catIds['nuts-dry-fruits'],
                'old_price'   => 850,
                'new_price'   => 720,
                'purchase_price' => 450,
                'stock'       => 85,
                'description' => 'Premium grade raw California Almonds — crunchy, naturally sweet, and packed with vitamin E, protein, and healthy fats.',
                'meta_title'  => 'California Almonds – Premium Raw | Khadyobitan',
                'meta_description' => 'Premium raw California almonds. Rich in Vitamin E, heart healthy, brain health support.',
                'meta_keyword' => 'almonds, california almonds, raw almonds, vitamin E',
                'topsale'     => 1,
                'new_arrival' => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Premium Cashews (W320)',
                'slug'        => 'premium-cashews-w320',
                'category_id' => $catIds['nuts-dry-fruits'],
                'old_price'   => 780,
                'new_price'   => 680,
                'purchase_price' => 420,
                'stock'       => 70,
                'description' => 'Whole W320 grade cashew nuts — creamy, buttery, and perfect for snacking, cooking, and making cashew milk or cream.',
                'meta_title'  => 'Premium Cashews W320 – Whole Grade | Khadyobitan',
                'meta_description' => 'W320 grade whole cashew nuts. Rich in zinc, magnesium and healthy fats.',
                'meta_keyword' => 'cashews, W320 cashews, premium cashews, whole cashews',
                'top_selling' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Walnuts (Halves)',
                'slug'        => 'walnuts-halves',
                'category_id' => $catIds['nuts-dry-fruits'],
                'old_price'   => 920,
                'new_price'   => 780,
                'purchase_price' => 480,
                'stock'       => 48,
                'description' => 'Premium walnut halves with a rich, slightly bitter flavor. Loaded with omega-3 fatty acids and antioxidants for brain health.',
                'meta_title'  => 'Walnuts Halves – Omega-3 Brain Food | Khadyobitan',
                'meta_description' => 'Premium walnut halves. Rich in omega-3, brain health support, anti-inflammatory.',
                'meta_keyword' => 'walnuts, walnut halves, omega-3, brain food',
                'top_rated'   => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Organic Spices
            [
                'name'        => 'Organic Turmeric Powder',
                'slug'        => 'organic-turmeric-powder',
                'category_id' => $catIds['organic-spices'],
                'old_price'   => 280,
                'new_price'   => 220,
                'purchase_price' => 130,
                'stock'       => 140,
                'description' => 'Vibrant golden organic turmeric powder with high curcumin content. A powerful anti-inflammatory spice essential for cooking and golden milk.',
                'meta_title'  => 'Organic Turmeric Powder – High Curcumin | Khadyobitan',
                'meta_description' => 'Organic turmeric powder with high curcumin content. Anti-inflammatory, immunity boost.',
                'meta_keyword' => 'turmeric powder, organic turmeric, curcumin, golden spice',
                'topsale'     => 1,
                'top_selling' => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Organic Black Pepper (Whole)',
                'slug'        => 'organic-black-pepper-whole',
                'category_id' => $catIds['organic-spices'],
                'old_price'   => 420,
                'new_price'   => 350,
                'purchase_price' => 210,
                'stock'       => 90,
                'description' => 'Premium whole black peppercorns with bold, complex flavor and high piperine content. The king of spices, freshly ground for best taste.',
                'meta_title'  => 'Organic Black Pepper Whole – High Piperine | Khadyobitan',
                'meta_description' => 'Organic whole black peppercorns from Kerala. High piperine, digestive aid, anti-inflammatory.',
                'meta_keyword' => 'black pepper, whole peppercorns, organic spice, piperine',
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Ceylon Cinnamon Sticks',
                'slug'        => 'ceylon-cinnamon-sticks',
                'category_id' => $catIds['organic-spices'],
                'old_price'   => 520,
                'new_price'   => 450,
                'purchase_price' => 280,
                'stock'       => 65,
                'description' => 'True Ceylon Cinnamon (Cinnamomum verum) — delicate, sweet, and far superior to common cassia. Low in coumarin, safe for daily use.',
                'meta_title'  => 'Ceylon Cinnamon Sticks – True Sri Lanka | Khadyobitan',
                'meta_description' => 'Organic true Ceylon cinnamon from Sri Lanka. Low coumarin, blood sugar regulation, antioxidant.',
                'meta_keyword' => 'ceylon cinnamon, true cinnamon, cinnamon sticks, Sri Lanka cinnamon',
                'top_rated'   => 1,
                'new_arrival' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Herbal Teas
            [
                'name'        => 'Organic Green Tea',
                'slug'        => 'organic-green-tea',
                'category_id' => $catIds['herbal-teas'],
                'old_price'   => 450,
                'new_price'   => 380,
                'purchase_price' => 230,
                'stock'       => 110,
                'description' => 'Premium loose leaf organic green tea with a smooth, slightly vegetal flavor. Rich in catechins and L-theanine for calm, focused energy.',
                'meta_title'  => 'Organic Green Tea Loose Leaf – Catechin Rich | Khadyobitan',
                'meta_description' => 'Organic loose leaf green tea. Rich in catechins, boosts metabolism, heart health.',
                'meta_keyword' => 'green tea, organic tea, loose leaf tea, catechins, antioxidant',
                'topsale'     => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Chamomile Herbal Tea',
                'slug'        => 'chamomile-herbal-tea',
                'category_id' => $catIds['herbal-teas'],
                'old_price'   => 490,
                'new_price'   => 420,
                'purchase_price' => 260,
                'stock'       => 75,
                'description' => 'Whole dried chamomile flowers for a soothing, caffeine-free herbal infusion. Known for its calming properties and gentle floral aroma.',
                'meta_title'  => 'Chamomile Herbal Tea – Caffeine Free | Khadyobitan',
                'meta_description' => 'Organic chamomile tea, caffeine-free. Promotes sleep, reduces anxiety, digestive comfort.',
                'meta_keyword' => 'chamomile tea, herbal tea, caffeine free, sleep tea',
                'top_rated'   => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Tulsi (Holy Basil) Tea',
                'slug'        => 'tulsi-holy-basil-tea',
                'category_id' => $catIds['herbal-teas'],
                'old_price'   => 400,
                'new_price'   => 340,
                'purchase_price' => 200,
                'stock'       => 88,
                'description' => 'Dried organic Tulsi leaves — an Ayurvedic adaptogen revered for stress relief, immune support, and respiratory health.',
                'meta_title'  => 'Tulsi Holy Basil Tea – Ayurvedic Adaptogen | Khadyobitan',
                'meta_description' => 'Organic tulsi tea, ayurvedic adaptogen. Stress relief, immune support, respiratory health.',
                'meta_keyword' => 'tulsi tea, holy basil, ayurvedic tea, adaptogen',
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // Health Foods
            [
                'name'        => 'Organic Rolled Oats',
                'slug'        => 'organic-rolled-oats',
                'category_id' => $catIds['health-foods'],
                'old_price'   => 420,
                'new_price'   => 350,
                'purchase_price' => 210,
                'stock'       => 120,
                'description' => 'Thick-cut organic rolled oats that cook to a creamy, hearty porridge. Rich in beta-glucan fiber for heart health and sustained energy.',
                'meta_title'  => 'Organic Rolled Oats – Beta-Glucan Heart Health | Khadyobitan',
                'meta_description' => 'Organic whole grain rolled oats. High in beta-glucan, heart healthy, sustained energy.',
                'meta_keyword' => 'rolled oats, oatmeal, organic oats, beta-glucan, whole grain',
                'topsale'     => 1,
                'new_arrival' => 1,
                'feature_product' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Organic Wheat Flour (Atta)',
                'slug'        => 'organic-wheat-flour',
                'category_id' => $catIds['health-foods'],
                'old_price'   => 220,
                'new_price'   => 180,
                'purchase_price' => 110,
                'stock'       => 200,
                'description' => 'Stone-ground organic whole wheat flour made from heritage wheat varieties. Perfect for chapati, roti, and traditional baking.',
                'meta_title'  => 'Organic Wheat Flour Atta – Stone Ground | Khadyobitan',
                'meta_description' => 'Stone-ground organic whole wheat atta. Rich in fiber, no bleaching agents, heritage variety.',
                'meta_keyword' => 'wheat flour, atta, organic flour, stone ground, chapati flour',
                'top_selling' => 1,
                'status'      => 1,
                'type'        => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        // Normalize all products to have identical keys (fill missing flags with null/0)
        $defaults = [
            'subcategory_id'   => null,
            'childcategory_id' => null,
            'brand_id'         => null,
            'type'             => 1,
            'purchase_price'   => 0,
            'old_price'        => null,
            'warranty'         => null,
            'stock_alert'      => null,
            'pro_barcode'      => null,
            'pro_video'        => null,
            'meta_title'       => null,
            'meta_description' => null,
            'meta_keyword'     => null,
            'topsale'          => null,
            'new_arrival'      => 0,
            'top_rated'        => 0,
            'top_selling'      => 0,
            'feature_product'  => null,
            'campaign_id'      => null,
            'shipping_charge_dhaka'          => null,
            'shipping_charge_outside_dhaka'  => null,
            'shipping_title_dhaka'           => null,
            'shipping_amount_dhaka'          => null,
            'shipping_title_outside_dhaka'   => null,
            'shipping_amount_outside_dhaka'  => null,
        ];

        $normalized = array_map(fn($p) => array_merge($defaults, $p), $products);

        DB::table('products')->insert($normalized);

        $this->command->info('✅ Seeded ' . count($categories) . ' categories and ' . count($products) . ' products.');
    }
}
